import { useCallback, useEffect, useMemo, useState } from "react";
import { FiDownload, FiPlus, FiSearch, FiX } from "react-icons/fi";
import toast from "react-hot-toast";
import MainLayout from "../../Layouts/MainLayout";
import EmptyState from "../UI/EmptyState";
import PageHeader from "../UI/PageHeader";
import Spinner from "../UI/Spinner";
import { apiMessage } from "../../services/api";
import { createRecord, exportRecordsCsv, listRecords, titleCase, updateRecord } from "../../services/serviceManagement";

const configs = {
  request: { meta: "Service catalog", title: "Requests", description: "Submit, approve and fulfil employee service requests.", button: "Create request", statuses: ["submitted", "pending_approval", "approved", "in_fulfillment", "completed"], fields: ["category"] },
  problem: { meta: "Root cause", title: "Problems", description: "Connect recurring incidents to known errors and permanent fixes.", button: "New problem", statuses: ["investigating", "known_error", "resolved", "closed"], fields: ["rootCause", "workaround"] },
  change: { meta: "Change enablement", title: "Changes", description: "Assess risk, obtain CAB approval and coordinate implementation windows.", button: "New change", statuses: ["draft", "awaiting_cab", "approved", "scheduled", "implemented"], fields: ["risk", "impact", "implementationPlan", "testPlan", "rollbackPlan"] },
  ci: { meta: "Configuration", title: "CMDB", description: "Track services, assets, owners and the relationships behind business impact.", button: "Add CI", statuses: ["active", "maintenance", "retired"], fields: ["ciType", "environment", "location", "serialNumber"] },
  knowledge: { meta: "Self service", title: "Knowledge", description: "Publish practical answers that help people resolve common issues faster.", button: "New article", statuses: ["draft", "review", "published", "archived"], fields: ["category"] },
};

const inputLabels = { rootCause: "Root cause", workaround: "Workaround", risk: "Risk", impact: "Impact", implementationPlan: "Implementation plan", testPlan: "Test plan", rollbackPlan: "Rollback plan", ciType: "CI type", environment: "Environment", location: "Location", serialNumber: "Serial number", category: "Category" };

const ServiceModulePage = ({ type }) => {
  const config = configs[type];
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: "", description: "", status: config.statuses[0], priority: "medium" });
  const load = useCallback(async () => { setLoading(true); try { setRecords((await listRecords(type, { search: search || undefined })).records); } catch (error) { toast.error(apiMessage(error, `Could not load ${config.title.toLowerCase()}.`)); } finally { setLoading(false); } }, [config.title, search, type]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const stats = useMemo(() => ({ total: records.length, active: records.filter((r) => !["completed", "closed", "implemented", "resolved", "retired", "archived"].includes(r.status)).length, overdue: records.filter((r) => r.dueAt && new Date(r.dueAt) < new Date() && !["completed", "closed", "implemented", "resolved"].includes(r.status)).length }), [records]);
  const submit = async (event) => { event.preventDefault(); try { const saved = await createRecord(type, form); setRecords((items) => [saved, ...items]); setShowForm(false); setForm({ title: "", description: "", status: config.statuses[0], priority: "medium" }); toast.success(`${saved.number} created`); } catch (error) { toast.error(apiMessage(error, "Could not create record.")); } };
  const cycleStatus = async (record) => { const next = config.statuses[(config.statuses.indexOf(record.status) + 1) % config.statuses.length]; try { const saved = await updateRecord(type, record.id, { status: next }); setRecords((items) => items.map((item) => item.id === saved.id ? saved : item)); } catch (error) { toast.error(apiMessage(error, "Could not update status.")); } };

  return <MainLayout><PageHeader meta={config.meta} title={config.title} description={config.description} actions={<div className="flex gap-2"><button className="btn btn-ghost" onClick={() => exportRecordsCsv(records, `${type}-records.csv`)}><FiDownload /> Export</button><button className="btn bg-slate-950 text-white hover:bg-cyan-700" onClick={() => setShowForm(true)}><FiPlus /> {config.button}</button></div>} />
    <div className="mb-6 grid gap-4 sm:grid-cols-3">{Object.entries(stats).map(([label, value]) => <div key={label} className="motion-card rounded-2xl border border-base-300 bg-base-100 p-5 shadow-sm"><p className="text-sm text-base-content/60">{titleCase(label)}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div>
    <div className="mb-4 flex items-center gap-3 rounded-2xl border border-base-300 bg-base-100 px-4"><FiSearch className="text-base-content/50"/><input className="input w-full border-0 bg-transparent focus:outline-none" placeholder={`Search ${config.title.toLowerCase()}...`} value={search} onChange={(e) => setSearch(e.target.value)} /></div>
    {loading ? <div className="rounded-2xl bg-base-100 p-12"><Spinner label={`Loading ${config.title.toLowerCase()}...`} /></div> : records.length === 0 ? <EmptyState title={`No ${config.title.toLowerCase()} found`} description={`Create the first persisted ${type} record to begin this workflow.`} /> : <div className="overflow-x-auto rounded-2xl border border-base-300 bg-base-100 shadow-sm"><table className="table"><thead><tr><th>Record</th><th>Status</th><th>Priority / risk</th><th>Owner</th><th>Updated</th></tr></thead><tbody>{records.map((record) => <tr key={record.id} className="hover"><td><p className="font-mono text-xs font-bold text-cyan-700">{record.number}</p><p className="font-semibold">{record.title}</p><p className="max-w-md truncate text-xs text-base-content/55">{record.description}</p></td><td><button className="badge badge-outline cursor-pointer" onClick={() => cycleStatus(record)} title="Advance status">{record.statusLabel}</button></td><td><span className="badge badge-ghost">{titleCase(record.risk || record.priority)}</span></td><td>{record.ownerName}</td><td>{new Date(record.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}
    {showForm && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm"><form onSubmit={submit} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-base-100 p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-600">{config.meta}</p><h2 className="text-2xl font-black">{config.button}</h2></div><button type="button" className="btn btn-circle btn-ghost" onClick={() => setShowForm(false)}><FiX /></button></div><div className="space-y-4"><input required minLength="3" className="input input-bordered w-full" placeholder="Title" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })}/><textarea className="textarea textarea-bordered min-h-28 w-full" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/><div className="grid gap-4 sm:grid-cols-2"><select className="select select-bordered w-full" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{config.statuses.map((s) => <option key={s} value={s}>{titleCase(s)}</option>)}</select><select className="select select-bordered w-full" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{["low", "medium", "high", "urgent"].map((p) => <option key={p}>{p}</option>)}</select></div>{config.fields.map((field) => field === "risk" ? <select key={field} className="select select-bordered w-full" value={form[field] || ""} onChange={(e) => setForm({ ...form, [field]: e.target.value })}><option value="">Select risk</option>{["low", "medium", "high", "critical"].map((p) => <option key={p}>{p}</option>)}</select> : ["rootCause", "workaround", "impact", "implementationPlan", "testPlan", "rollbackPlan"].includes(field) ? <textarea key={field} className="textarea textarea-bordered w-full" placeholder={inputLabels[field]} value={form[field] || ""} onChange={(e) => setForm({ ...form, [field]: e.target.value })}/> : <input key={field} className="input input-bordered w-full" placeholder={inputLabels[field]} value={form[field] || ""} onChange={(e) => setForm({ ...form, [field]: e.target.value })}/>)}</div><button className="btn mt-6 w-full bg-cyan-500 text-slate-950 hover:bg-cyan-400">Create persisted record</button></form></div>}
  </MainLayout>;
};
export default ServiceModulePage;
