import { FiArrowRight, FiCheck, FiLayers, FiShield, FiZap } from "react-icons/fi";
import { Link } from "react-router-dom";
import HeroProductScene from "../components/Landing/HeroProductScene";
import ThemeToggle from "../components/UI/ThemeToggle";

const LandingPage = () => {
  return <div className="landing-page min-h-screen overflow-hidden bg-slate-950 text-white">
    <nav className="relative z-30 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link to="/" className="flex items-center gap-3 font-bold"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400 text-slate-950"><FiCheck /></span><span className="text-xl">ClearQueue</span></Link><div className="hidden gap-8 text-sm text-slate-300 md:flex"><a href="#product">Product</a><a href="#features">Features</a><a href="#insights">Insights</a></div><div className="flex items-center gap-3"><ThemeToggle darkSurface /><Link to="/login" className="px-3 py-2 text-sm font-medium text-slate-200">Sign in</Link><Link to="/register" className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950">Start free</Link></div></nav>
    <main>
      <section className="landing-hero relative px-5 pb-24 pt-20 lg:px-8 lg:pt-28"><div className="landing-orb landing-orb-one" /><div className="landing-orb landing-orb-two" /><div className="landing-grid" /><div className="relative z-10 mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.9fr_1.1fr]">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-semibold text-cyan-200"><FiZap /> A calmer way to run support</span><h1 className="mt-7 text-5xl font-bold leading-[1.04] tracking-tight sm:text-6xl">Service work,<br/><span className="bg-gradient-to-r from-cyan-300 via-blue-300 to-violet-300 bg-clip-text text-transparent">beautifully clear.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">One thoughtful workspace for reporting issues, managing incidents, and keeping every customer in the loop.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/register" className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950 transition hover:-translate-y-0.5 hover:bg-cyan-300">Create your workspace <FiArrowRight /></Link><a href="#product" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-semibold">See the product</a></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-400">{["Fast setup", "Secure by design", "Customer friendly"].map(item=><span key={item} className="flex items-center gap-2"><FiCheck className="text-cyan-300" />{item}</span>)}</div></div>
        <HeroProductScene />
      </div></section>
      <section id="features" className="bg-slate-50 px-5 py-24 text-slate-950 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-700">Designed for momentum</p><h2 className="mt-3 max-w-2xl text-4xl font-bold">Everything support teams need. Nothing they don’t.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{[{icon:<FiLayers/>,title:"One shared queue",text:"Bring requests, owners, priorities, and status into one dependable view."},{icon:<FiShield/>,title:"Private when needed",text:"Separate internal collaboration from customer-visible updates with confidence."},{icon:<FiZap/>,title:"Fast customer intake",text:"A focused two-field form gets people help without making them learn your process."}].map(card=><article key={card.title} className="motion-card rounded-2xl border border-slate-200 bg-white p-7"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-cyan-100 text-xl text-cyan-800">{card.icon}</span><h3 className="mt-5 text-xl font-semibold">{card.title}</h3><p className="mt-3 leading-7 text-slate-600">{card.text}</p></article>)}</div></div></section>
      <section id="insights" className="bg-white px-5 py-24 text-slate-950 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-violet-700">From the journal</p><h2 className="mt-3 text-4xl font-bold">Ideas for better service</h2></div><span className="hidden text-sm text-slate-500 md:block">Fresh articles are coming soon.</span></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[{tag:"Operations",title:"A practical guide to calmer incident response",color:"from-cyan-500 to-blue-700"},{tag:"Customer experience",title:"What a truly useful ticket update looks like",color:"from-violet-500 to-fuchsia-700"},{tag:"Service design",title:"Building workflows your team will actually use",color:"from-emerald-500 to-teal-700"}].map((blog,index)=><article key={blog.title} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className={`relative h-44 bg-gradient-to-br ${blog.color}`}><div className="absolute inset-0 opacity-30 landing-card-grid"/><span className="absolute bottom-4 left-4 rounded-full bg-white/15 px-3 py-1 text-xs text-white backdrop-blur">Coming soon</span></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-700">{blog.tag}</p><h3 className="mt-3 text-xl font-semibold leading-7">{blog.title}</h3><p className="mt-5 text-sm text-slate-400">Article {String(index+1).padStart(2,"0")} · 6 min read</p></div></article>)}</div></div></section>
    </main>
    <footer className="border-t border-white/10 bg-slate-950 px-5 py-12 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3 font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-cyan-400 text-slate-950"><FiCheck /></span>ClearQueue</div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-400">Modern incident management for teams that care about the customer experience.</p></div><div className="flex gap-6 text-sm text-slate-400"><a href="#product">Product</a><a href="#features">Features</a><Link to="/login">Sign in</Link></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-6 text-xs text-slate-500">© 2026 ClearQueue. Built for better service.</div></footer>
  </div>;
};

export default LandingPage;
