import { motion, useReducedMotion } from "framer-motion";
import { FiArrowRight, FiCheck, FiLayers, FiShield, FiTrendingUp, FiZap } from "react-icons/fi";
import { Link } from "react-router-dom";
import HeroProductScene from "../components/Landing/HeroProductScene";
import ThemeToggle from "../components/UI/ThemeToggle";

const ease = [0.2, 0.8, 0.2, 1];
const reveal = { hidden: { opacity: 0, y: 34 }, visible: { opacity: 1, y: 0, transition: { duration: 0.72, ease } } };

const Reveal = ({ children, className = "", delay = 0 }) => (
  <motion.div className={className} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.22 }} transition={{ delay }}>
    {children}
  </motion.div>
);

const WordRise = ({ children, className = "" }) => {
  const reducedMotion = useReducedMotion();
  return <span className={`landing-word-rise ${className}`}>{String(children).split(" ").map((word, index) => <motion.span key={`${word}-${index}`} initial={reducedMotion ? false : { y: "110%", opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: .72, delay: .18 + index * .075, ease }}><span>{word}</span>{index < String(children).split(" ").length - 1 && " "}</motion.span>)}</span>;
};

const LandingPage = () => {
  const features = [
    { icon: <FiLayers />, title: "One connected workspace", text: "Incidents, requests, changes, problems and assets move together without losing context." },
    { icon: <FiShield />, title: "Private when needed", text: "Give staff a secure place to collaborate while customers receive clear, useful updates." },
    { icon: <FiZap />, title: "Built for momentum", text: "Smart queues, SLA signals and knowledge guidance keep the next action obvious." },
  ];
  const stories = [
    { eyebrow: "Workflow intelligence", title: "From request to resolution, every handoff stays visible.", text: "Approvals, ownership, SLA pressure and fulfilment live in one calm timeline—so teams spend less time chasing updates and more time solving the work.", image: "/images/request-workflow.png", points: ["Clear approval checkpoints", "Live SLA and ownership signals", "A complete operational history"] },
    { eyebrow: "Knowledge that works", title: "Turn repeated questions into instant, trusted answers.", text: "Build a practical self-service layer from the work your team already knows. Customers find answers sooner, while agents keep guidance current.", image: "/images/knowledge-discovery.png", points: ["Searchable support knowledge", "Articles connected to real issues", "Faster, consistent resolutions"], reverse: true },
  ];

  return <div className="landing-page min-h-screen overflow-hidden bg-slate-950 text-white">
    <nav className="landing-nav sticky top-0 z-40 mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3 font-bold"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-400/20"><FiCheck /></span><span className="text-xl">ClearQueue</span></Link><div className="hidden gap-8 text-sm text-slate-300 md:flex"><a href="#product">Product</a><a href="#features">Features</a><a href="#stories">How it works</a><a href="#insights">Insights</a></div><div className="flex items-center gap-2 sm:gap-3"><ThemeToggle darkSurface /><Link to="/login" className="hidden px-3 py-2 text-sm font-medium text-slate-200 sm:block">Sign in</Link><Link to="/register" className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950 transition hover:-translate-y-0.5">Start free</Link></div></nav>
    <main>
      <section id="product" className="landing-hero relative px-5 pb-20 pt-20 lg:px-8 lg:pb-28 lg:pt-28"><div className="landing-orb landing-orb-one"/><div className="landing-orb landing-orb-two"/><div className="landing-grid"/><div className="relative z-10 mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[.88fr_1.12fr]">
        <div><motion.span initial={{ opacity: 0, scale: .92 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .55 }} className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1 text-xs font-semibold text-cyan-200"><FiZap/> The service workspace, reimagined</motion.span><h1 className="mt-7 text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl xl:text-7xl"><WordRise>Make complex service work</WordRise><br/><WordRise className="landing-gradient-text">feel beautifully clear.</WordRise></h1><motion.p initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .8, duration: .6 }} className="mt-7 max-w-xl text-lg leading-8 text-slate-300">A thoughtful command centre for every request, incident and change—designed to help teams move faster without making customers feel left behind.</motion.p><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1 }} className="mt-9 flex flex-wrap gap-3"><Link to="/register" className="landing-primary-cta flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Create your workspace <FiArrowRight/></Link><a href="#stories" className="rounded-xl border border-white/15 bg-white/5 px-5 py-3 font-semibold backdrop-blur transition hover:bg-white/10">Explore the flow</a></motion.div><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.1 }} className="mt-9 flex flex-wrap gap-5 text-sm text-slate-400">{["Fast setup", "Secure by design", "Customer friendly"].map(item => <span key={item} className="flex items-center gap-2"><FiCheck className="text-cyan-300"/>{item}</span>)}</motion.div></div>
        <motion.div initial={{ opacity: 0, x: 44, scale: .96 }} animate={{ opacity: 1, x: 0, scale: 1 }} transition={{ delay: .35, duration: .9, ease }}><HeroProductScene/></motion.div>
      </div></section>

      <section className="landing-proof border-y border-white/10 px-5 py-8 lg:px-8"><div className="mx-auto grid max-w-7xl gap-6 sm:grid-cols-3">{[["92%", "SLA health at a glance"], ["6 modules", "One connected source of truth"], ["360°", "Context around every service"]].map(([value, label], index) => <Reveal key={value} delay={index * .08} className="flex items-center gap-4 border-white/10 sm:border-r sm:last:border-0"><strong className="text-3xl font-black text-cyan-300">{value}</strong><span className="max-w-[10rem] text-sm leading-5 text-slate-400">{label}</span></Reveal>)}</div></section>

      <section id="features" className="bg-slate-50 px-5 py-24 text-slate-950 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal><p className="landing-kicker">Designed for momentum</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-5xl">A service platform that feels as considered as the experience you want to deliver.</h2></Reveal><div className="mt-14 grid gap-5 md:grid-cols-3">{features.map((card, index) => <Reveal key={card.title} delay={index * .08}><article className="landing-feature-card group h-full rounded-3xl border border-slate-200 bg-white p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950 text-xl text-cyan-300 transition group-hover:-rotate-6 group-hover:scale-110">{card.icon}</span><p className="mt-10 text-xs font-bold text-slate-400">0{index + 1}</p><h3 className="mt-3 text-2xl font-bold">{card.title}</h3><p className="mt-4 leading-7 text-slate-600">{card.text}</p></article></Reveal>)}</div></div></section>

      <section id="stories" className="landing-stories px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl space-y-28">{stories.map((story) => <div key={story.title} className="grid items-center gap-12 lg:grid-cols-2 lg:gap-20"><Reveal className={story.reverse ? "lg:order-2" : ""}><div className="landing-image-frame"><img src={story.image} alt="" loading="lazy"/><span className="landing-image-glow"/></div></Reveal><Reveal className={story.reverse ? "lg:order-1" : ""}><p className="landing-kicker text-cyan-300">{story.eyebrow}</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">{story.title}</h2><p className="mt-6 text-lg leading-8 text-slate-300">{story.text}</p><div className="mt-8 space-y-4">{story.points.map(point => <div key={point} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-cyan-300/10 text-cyan-300"><FiCheck/></span><span className="text-slate-200">{point}</span></div>)}</div></Reveal></div>)}</div></section>

      <section className="bg-slate-100 px-5 py-24 text-slate-950 lg:px-8"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] bg-slate-950 text-white lg:grid-cols-[1.05fr_.95fr]"><Reveal className="flex flex-col justify-center p-8 sm:p-12 lg:p-16"><span className="landing-kicker text-cyan-300">Built around people</span><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">The calm behind a high-performing service desk.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">See workload, risk and customer impact clearly enough to make the next decision with confidence.</p><div className="mt-8 flex items-center gap-3 text-sm text-slate-400"><FiTrendingUp className="text-cyan-300"/> Live operational clarity, without dashboard noise.</div></Reveal><div className="min-h-[25rem]"><img src="/images/service-desk-team.png" alt="Service desk professional reviewing operational dashboards" loading="lazy" className="h-full w-full object-cover"/></div></div></section>

      <section id="insights" className="px-5 py-24 text-slate-950 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><Reveal className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="landing-kicker text-violet-700">From the journal</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Ideas for better service.</h2></div><Link to="/register" className="flex items-center gap-2 font-semibold text-cyan-700">Put the ideas to work <FiArrowRight/></Link></Reveal><div className="mt-12 grid gap-6 md:grid-cols-3">{[{tag:"Operations",title:"A practical guide to calmer incident response",image:"/images/service-operations-hero.png"},{tag:"Customer experience",title:"What a truly useful ticket update looks like",image:"/images/service-desk-team.png"},{tag:"Service design",title:"Build workflows your team will actually use",image:"/images/request-workflow.png"}].map((blog,index) => <Reveal key={blog.title} delay={index * .08}><article className="landing-journal-card group overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="h-48 overflow-hidden"><img src={blog.image} alt="" loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-700">{blog.tag}</p><h3 className="mt-3 text-xl font-bold leading-7">{blog.title}</h3><p className="mt-6 text-sm text-slate-400">Article {String(index + 1).padStart(2, "0")} · 6 min read</p></div></article></Reveal>)}</div></div></section>

      <section className="px-5 pb-24 lg:px-8"><Reveal className="mx-auto max-w-7xl rounded-[2rem] border border-cyan-300/20 bg-gradient-to-br from-cyan-400 to-blue-500 p-8 text-slate-950 sm:p-12 lg:flex lg:items-center lg:justify-between lg:p-16"><div><p className="text-sm font-black uppercase tracking-[.2em]">Ready when your team is</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-5xl">Make the next service moment your clearest one yet.</h2></div><Link to="/register" className="mt-8 inline-flex shrink-0 items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-semibold text-white transition hover:-translate-y-1 lg:mt-0">Start with ClearQueue <FiArrowRight/></Link></Reveal></section>
    </main>
    <footer className="border-t border-white/10 bg-slate-950 px-5 py-12 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3 font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-cyan-400 text-slate-950"><FiCheck/></span>ClearQueue</div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-400">Modern service management for teams that care about every customer experience.</p></div><div className="flex flex-wrap gap-6 text-sm text-slate-400"><a href="#product">Product</a><a href="#features">Features</a><a href="#stories">How it works</a><Link to="/login">Sign in</Link></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-6 text-xs text-slate-500">© 2026 ClearQueue. Built for better service.</div></footer>
  </div>;
};

export default LandingPage;
